package com.app.studentdiary.info;

public enum RvType {
    RV_TYPE_TEACHER_REGS,
    RV_TYPE_ATTENDANCE,
    RV_TYPE_STUDENT_ATTENDANCE,
    RV_TYPE_STUDENT_MARKS,
    RV_TYPE_ACTIVITY,
    RV_TYPE_PARENT_MARKS,
    RV_TYPE_PARENT_ACTIVITY,
    RV_TYPE_CHATS,
    RV_TYPE_COMMENTS,
    RV_TYPE_SCHOOL_NOTICES,
    RV_TYPE_PARENT_SCHOOL_NOTICES,
    RV_TYPE_FEES
}
